name:                molecular-ast
version:             0.1.0.0
github:              "githubuser/fraser-dunlop"
license:             BSD3
author:              "Fraser Dunlop"
maintainer:          "fraser.dunlop@gmail.com"
copyright:           "2020 Fraser Dunlop"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/molecular-ast#readme>

dependencies:
- async
- base >= 4.7 && < 5
- base-compat
- binary
- deepseq
- deriving-compat
- hypertypes
- pretty 
- constraints
- containers
- generic-constraints
- generic-data
- lattices
- lens
- megaparsec
- monad-st
- mtl
- random-extras
- random-fu
- random-source
- template-haskell
- text
- type-sets
- cmptype
- STMonadTrans

default-extensions:
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveGeneric
- DerivingStrategies
- GADTs
- GeneralizedNewtypeDeriving
- LambdaCase
- MultiParamTypeClasses
- RankNTypes
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeApplications
- TypeOperators
- TypeFamilies

library:
  source-dirs: src

executables:
  molecular-ast-test-exe:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -Wall
    - -Wcompat
    - -Wredundant-constraints
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - molecular-ast
    - hypertypes
    - text

tests:
  molecular-ast-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -Wall
    - -Wcompat
    - -Wredundant-constraints
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - molecular-ast
    - hypertypes
    - text
